package pk.development.pro.smshacker;

public class Constants {
    public static final byte[] GSMTAP_HEADER = {
            0x02,0x04,0x01,0x00,0x03,0x69,0x00,0x00,0x00,0x07,(byte)0xA2,(byte)0xEA,0x08,0x00,0x00,0x00
    };
    public static final int MESSAGE_RECEIVED = 0x22;
    public static final String SEND_PDU_CMD = "AT+CMGS=17\r";
    public static final  String[] AT_GSM_COMMANDS = {
            "AT+CSIM=14,\\\"A0A40000027F20\\\"",
            "AT+CSIM=42,\\\"A088000010FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\\\"",
            "AT+CSIM=14,\\\"A0A40000026F20\\\"",
            "AT+CSIM=10,\\\"A0B0000009\\\"",
            "AT+CSIM=14,\\\"A0A40000026F7E\\\"",
            "AT+CSIM=10,\\\"A0B000000B\\\""};

    public final static String[] COMMANDS = {
            "ATI#Status (Manufacturer, Model, Revision, IMEI, capabilities)",
            "AT#Check AT is working",
            "AT+CSIM=14,\"A0A40000027F20\"#gsm algo",
            "AT+CSIM=42,\"A088000010FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\"#gsm algo",
            "AT+CSIM=14,\"A0A40000026F20\"#gsm algo",
            "AT+CSIM=10,\"A0B0000009\"#gsm algo",
            "AT+CSIM=14,\"A0A40000026F7E\"#gsm algo",
            "AT+CSIM=10,\"A0B000000B\"#gsm algo",
            "ATE#Echo data on terminal",
            "AT+CSIM=14,\"A0A40000026F07\"#gsm algo",
            "AT+CSIM=10,\"A0B0000009\"#gsm algo",
            "AT+CSIM=14,\"A0A40000027F07\"#gsm algo",
            "AT+CSIM=10,\"A0B0000009\"#gsm algo",
            "AT+CNUM#Get Sim Phone number",
            "AT+CIMI#Get device IMSI",
            "AT+CMGF?#Check if modem in pdu(0) or (1)text mode",
            "AT+CMGF=0#Put modem in pdu mode",
            "AT+CREG?#Network Registration info",
            "AT+CREG=1#no data",
            "AT+CREG=2#Set this to get current cell id in hex",
            "AT+CREG=3#no data",
            "AT+COPS?#Get current network info",
            "AT+CMGF=1#Put modem in text mode",
            "AT+CMGL=4#List all sms in pdu mode",
            "AT+CMGD=1,4#Delete all sms on modem",
            "AT^SYSCFG?#Check what mode modem in in GSM/3G etc",
            "AT^SYSINFO#System Info",
            "AT+CUSD?#Check ussd mode",
            "AT+IPR=?#list supported baud rates",
            "AT+IPR?#Current baud rate",
            "AT+IPR=115200#set baud to 115200",
            "AT+CPOL?#Preferred Operator List",
            "AT^SYSCFG=13,1,3FFFFFFF,2,4#Only mode GPRS/EDGE/2G",
            "AT^SYSCFG=14,2,3FFFFFFF,2,4#Only 3G/WCDMA mode",
            "AT^SYSCFG=2,1,3FFFFFFF,2,4#Prefferd GPRS/EDGE",
            "AT^SYSCFG=2,2,3FFFFFFF,2,4#Prefferd 3G/WCDMA",
            "AT^freqpref=?#Frequency preference command support",
            "AT^freqlock=?#Frequency lock/unlock command support",
            "AT^freqlock?#Current frequency lock support",
            "AT^freqlock=1,10837#Lock to specific frequency",
            "AT^freqlock=0#Unlock freqeuncy",
            "AT^freqpref?#Current setting",
            "AT^freqpref=1,412#Set frequency preference",
            "AT^freqpref=0,412#Disable frequency preference",
            "AT^fplmn=?#PLMN List control",
            "AT^fplmn?#Check the current PLMN List",
            "AT^u2diag?#current setting for U2diag",
            "AT^u2diag=0#Set for modem only mode",
            "AT^u2diag=1#set for modem+cdrom",
            "AT^u2diag=25#set for modem+cdrom+cardreader",
            "AT^u2diag=256#set for modem+cardreader",
            "AT^u2diag=276#no data",
            "AT^hsdpa?#Current setting for HSDPA",
            "AT^hsdpa=0#Disable HSDPA",
            "AT^hsdpa=1#Enable HSDPA",
            "AT^hspa?#Current setting for HSPA",
            "AT^hspa=1#Enable HSPA",
            "AT^hspa=0#Disable HSPA",
            "AT^hspa=1#Enable HSPA",
            "AT^hsupa?#Current setting for HSUPA",
            "AT^hsupa=?#HSUPA command support",
            "AT^hsupa=1#Enable HSUPA",
            "AT^hsupa=0#Disable HSUPA",
            "AT^hspa=?#Command support for HSPA",
            "AT^portsel=?#Portsel command support",
            "AT^portsel?#Current portsel setting",
            "AT^portsel=0#Set to PCUI port",
            "AT^portsel=1#Set to modem port",
            "AT^SPN=?#Read SPN command support",
            "AT^SPN=0#no data",
            "AT^SPN=1#no data",
            "AT^DSFLOWQRY#Query the DS flow",
            "AT^DSFLOWCLR#Reset DS traffic",
            "AT^SYSINFO#Get the system info 2 –Valid service, 3 – PS+CS service, 1 – Roaming, 3- GSM/GPRS mode, 1 – pin code locked, 2 – EDGE mode",
            "AT^cvoice=?#Circuit switch voice command support",
            "AT^cvoice?#Current setting for cvoice",
            "AT^pcmrecord?#PCM record setting",
            "AT^csnr=?#Signal to noise ratio command support",
            "AT^csnr?#Current signal to noise ratio",
            "AT^cmsr?#no data",
            "AT^cmsr=?#no data",
            "AT^anquery?#Signal condition",
            "AT^rscpcfg?#RSCP values",
            "AT^eciocfg?#ECIO values",
            "AT^slotcfg?#Slot configuration",
            "AT^ussdmode?#USSDMODE",
            "AT^yjcx?#no data",
            "AT^dnss?#DNSS setting",
            "AT^dnsp?#DNSP setting",
            "AT^CARDLOCK?#1no pin,2pin set,10attemps left"
    };

    public static final int ERROR_OPENING_PORT = 0x4141;
}
